### ISSUE TITLE
Ensure auto generated XML column mappings are unique

### ISSUE THREAD

**Issue by ollietulloch** [NHSDigital/ndr_import#114]
Given the below data:

```
<Section>
  <SubSection>
    <data_item code="01"/>
  </SubSection>
  <SubSection>
    <data_item code="02"/>
  </SubSection>
</Section>
<Section>
  <SubSection>
    <data_item code="03"/>
  </SubSection>
  <SubSection>
    <data_item code="04"/>
  </SubSection>
</Section>
```

And this column mapping:

```
- column: data_item
  klass: Some TestKlass
  rawtext_name: data_item
  xml_cell:
    relative_path: Section/SubSection
    attribute: code
    multiple: true
    increment_field_name: true
    build_new_record: false
  mappings:
  - field: data_item
  ```

This would result in duplicate mappings, where `data_item_3` has two column mappings.
```
- column: data_item
  klass: Some TestKlass
  rawtext_name: data_item_2
  xml_cell:
    relative_path: Section/SubSection
    attribute: code
    multiple: true
    increment_field_name: true
    build_new_record: false
  mappings:
  - field: data_item_2
- column: data_item
  klass: Some TestKlass
  rawtext_name: data_item_3
  xml_cell:
    relative_path: Section/SubSection
    attribute: code
    multiple: true
    increment_field_name: true
    build_new_record: false
  mappings:
  - field: data_item_3
- column: data_item
  klass: Some TestKlass
  rawtext_name: data_item_3
  xml_cell:
    relative_path: Section/SubSection
    attribute: code
    multiple: true
    increment_field_name: true
    build_new_record: false
  mappings:
  - field: data_item_3
 - column: data_item
  klass: Some TestKlass
  rawtext_name: data_item_4
  xml_cell:
    relative_path: Section/SubSection
    attribute: code
    multiple: true
    increment_field_name: true
    build_new_record: false
  mappings:
  - field: data_item_4
```

Summing the digits from xpaths eg [1, 2] and [2,1] does not create a unique column mapping.
